name: "Setup Axiom"
description: "Start a local Axiom deployment, set it up and create a personal token."
author: "Axiom"
branding:
  color: purple
  icon: x
inputs:
  axiom-version:
    description: "The Axiom version to use"
    default: "1.14.0"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/index.js"