name: Action

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  without-version:
    name: "Without version"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: setup-axiom
        uses: ./
  with-version:
    name: "With version"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        axiom: [1.13.0, 1.14.0]
    steps:
      - uses: actions/checkout@v2
      - name: setup-axiom
        uses: ./
        with:
          axiom-version: ${{ matrix.axiom }}
      # TODO: Verify the version